/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryType = IDL.Variant({
  'regular' : IDL.Null,
  'cinematics' : IDL.Null,
});
export const GearReview = IDL.Record({
  'gearName' : IDL.Text,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'publicationDate' : IDL.Int,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const MotorcycleReview = IDL.Record({
  'model' : IDL.Text,
  'manufacturer' : IDL.Text,
  'year' : IDL.Nat16,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'publicationDate' : IDL.Int,
  'rating' : IDL.Nat8,
});
export const Vlog = IDL.Record({
  'title' : IDL.Text,
  'categoryTags' : IDL.Vec(IDL.Text),
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'publicationDate' : IDL.Int,
  'category' : CategoryType,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGearReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat8, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addMotorcycleReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat16, IDL.Nat8, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addVlog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, CategoryType, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'getAllGearReviews' : IDL.Func([], [IDL.Vec(GearReview)], ['query']),
  'getAllMotorcycleReviews' : IDL.Func(
      [],
      [IDL.Vec(MotorcycleReview)],
      ['query'],
    ),
  'getAllVlogs' : IDL.Func([], [IDL.Vec(Vlog)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryType = IDL.Variant({
    'regular' : IDL.Null,
    'cinematics' : IDL.Null,
  });
  const GearReview = IDL.Record({
    'gearName' : IDL.Text,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'publicationDate' : IDL.Int,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const MotorcycleReview = IDL.Record({
    'model' : IDL.Text,
    'manufacturer' : IDL.Text,
    'year' : IDL.Nat16,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'publicationDate' : IDL.Int,
    'rating' : IDL.Nat8,
  });
  const Vlog = IDL.Record({
    'title' : IDL.Text,
    'categoryTags' : IDL.Vec(IDL.Text),
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'publicationDate' : IDL.Int,
    'category' : CategoryType,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addGearReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat8, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addMotorcycleReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat16, IDL.Nat8, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addVlog' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          CategoryType,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'getAllGearReviews' : IDL.Func([], [IDL.Vec(GearReview)], ['query']),
    'getAllMotorcycleReviews' : IDL.Func(
        [],
        [IDL.Vec(MotorcycleReview)],
        ['query'],
      ),
    'getAllVlogs' : IDL.Func([], [IDL.Vec(Vlog)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };