/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GearReview {
    gearName: string;
    reviewText: string;
    reviewerName: string;
    publicationDate: bigint;
    category: string;
    brand: string;
    rating: number;
}
export interface MotorcycleReview {
    model: string;
    manufacturer: string;
    year: number;
    reviewText: string;
    reviewerName: string;
    publicationDate: bigint;
    rating: number;
}
export interface Vlog {
    title: string;
    categoryTags: Array<string>;
    thumbnailUrl: string;
    description: string;
    publicationDate: bigint;
    category: CategoryType;
    videoUrl: string;
}
export enum CategoryType {
    regular = "regular",
    cinematics = "cinematics"
}
export interface backendInterface {
    addGearReview(gearName: string, category: string, brand: string, rating: number, reviewText: string, reviewerName: string): Promise<void>;
    addMotorcycleReview(model: string, manufacturer: string, year: number, rating: number, reviewText: string, reviewerName: string): Promise<void>;
    addVlog(title: string, description: string, videoUrl: string, thumbnailUrl: string, category: CategoryType, categoryTags: Array<string>): Promise<void>;
    getAllGearReviews(): Promise<Array<GearReview>>;
    getAllMotorcycleReviews(): Promise<Array<MotorcycleReview>>;
    getAllVlogs(): Promise<Array<Vlog>>;
}
import type { CategoryType as _CategoryType, Vlog as _Vlog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGearReview(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGearReview(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGearReview(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addMotorcycleReview(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMotorcycleReview(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMotorcycleReview(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addVlog(arg0: string, arg1: string, arg2: string, arg3: string, arg4: CategoryType, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVlog(arg0, arg1, arg2, arg3, to_candid_CategoryType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVlog(arg0, arg1, arg2, arg3, to_candid_CategoryType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async getAllGearReviews(): Promise<Array<GearReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGearReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGearReviews();
            return result;
        }
    }
    async getAllMotorcycleReviews(): Promise<Array<MotorcycleReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMotorcycleReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMotorcycleReviews();
            return result;
        }
    }
    async getAllVlogs(): Promise<Array<Vlog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVlogs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVlogs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CategoryType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryType): CategoryType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Vlog_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vlog): Vlog {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    categoryTags: Array<string>;
    thumbnailUrl: string;
    description: string;
    publicationDate: bigint;
    category: _CategoryType;
    videoUrl: string;
}): {
    title: string;
    categoryTags: Array<string>;
    thumbnailUrl: string;
    description: string;
    publicationDate: bigint;
    category: CategoryType;
    videoUrl: string;
} {
    return {
        title: value.title,
        categoryTags: value.categoryTags,
        thumbnailUrl: value.thumbnailUrl,
        description: value.description,
        publicationDate: value.publicationDate,
        category: from_candid_CategoryType_n6(_uploadFile, _downloadFile, value.category),
        videoUrl: value.videoUrl
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    regular: null;
} | {
    cinematics: null;
}): CategoryType {
    return "regular" in value ? CategoryType.regular : "cinematics" in value ? CategoryType.cinematics : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vlog>): Array<Vlog> {
    return value.map((x)=>from_candid_Vlog_n4(_uploadFile, _downloadFile, x));
}
function to_candid_CategoryType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): _CategoryType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): {
    regular: null;
} | {
    cinematics: null;
} {
    return value == CategoryType.regular ? {
        regular: null
    } : value == CategoryType.cinematics ? {
        cinematics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
